version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    network_mode: host
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yaml"]

  grafana:
    image: grafana/grafana:11.1.0
    network_mode: host
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
